# Generated by Django 3.0.9 on 2020-08-17 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('hamburguer', 'Hamburguer'), ('salgado', 'Salgado'), ('doce', 'Doce')], max_length=10),
        ),
    ]
