# Generated by Django 3.0.9 on 2020-08-18 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20200817_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_1',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='image_2',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
