# Generated by Django 3.0.9 on 2020-08-18 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_auto_20200819_0002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image_1',
            new_name='second_image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image_2',
            new_name='suggestion_image',
        ),
    ]
