# Generated by Django 3.0.9 on 2020-08-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_auto_20200819_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_description',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
